hp-networking/baremetal-network-provisioning

- baremetal_network_provisioning/common/constants.py
- baremetal_network_provisioning/common/exceptions.py
- baremetal_network_provisioning/ml2/hp_network_provisioning_driver.py
- baremetal_network_provisioning/ml2/mechanism_hp.py
- baremetal_network_provisioning/ml2/network_provisioning_api.py
- etc/ml2_conf_hp.ini
- etc/network_provisioning_conf.ini
This is initial mechanism driver for baremetal port provisioning
in neutron. This driver implementation is for front-end-driver.
Addressed below Vivek's comments .
1.	In network_provisioning_api.py - Please fix this @abc.abstractmethod
Done
2.	def delete_port(self, port_id):
Done
3.	"""create_network_precommit .""
Done
All comments below apply to mechanism_hp.py
Done
2. In L65 + port_dict = self._construct_port(context, False)
Should not pass False. In fact you should not pass anything for second argument.
Done
The second argument will be passed only in bind_port method.
1.	Please ensure all LOG statements adhere to Liberty logging standards. Also in LOG statements please refer the neutron port-id for initial troubleshooting help. For ex L141 - + LOG.debug("port bound using segment: %s", …
> Initial mechanism driver for baremetal provisioning

- baremetal_network_provisioning/db/migration/alembic_migrations/cli.py
- baremetal_network_provisioning/db/migration/alembic_migrations/env.py
- setup.cfg
This script executes the table creation for baremetal network
provisioning repo.
> Script for Migration file for baremetal network

- etc/hp_network_provisioning_conf.ini
- etc/ml2_conf_hp.ini
ini files fixed as per latest SDN controller REST API
> Ini file defect fixes for baremetal networking

- baremetal_network_provisioning/ml2/mechanism_hp.py
- baremetal_network_provisioning/tests/unit/ml2/test_mechanism_hp.py
adding unit test cases for mechanism_hp
> Add unit test cases for mech driver.

- baremetal_network_provisioning/tests/unit/ml2/test_hp_network_provisioning_driver.py
Fixed pep8 issue for the file test_hp_network_provisioning_driver.py
> Fixed pep8 issue

- baremetal_network_provisioning/db/bm_nw_provision_db.py
- baremetal_network_provisioning/db/bm_nw_provision_models.py
- baremetal_network_provisioning/db/migration/alembic_migrations/versions/3297cd3f2323_bm_nw_provision_models.py
Fixed the foreign key reference for the two tables. BNPNeutronPort & BNPSwitchPortMapping
> Fixed DB models 

- baremetal_network_provisioning/common/constants.py
- baremetal_network_provisioning/common/exceptions.py
- baremetal_network_provisioning/common/validators.py
- baremetal_network_provisioning/db/bm_nw_provision_db.py
- baremetal_network_provisioning/db/bm_nw_provision_models.py
- baremetal_network_provisioning/drivers/discovery_driver.py
- baremetal_network_provisioning/drivers/snmp_client.py
- baremetal_network_provisioning/ml2/extensions/bnp_switch.py
- baremetal_network_provisioning/ml2/extensions/switch.py
- baremetal_network_provisioning/ml2/hpironicextensiondriver.py
- setup.cfg
This patchset contains the implementation of extension and the
implementation of the discovery of the switch.
> Extension driver along with Discovery driver

- baremetal_network_provisioning/drivers/hp/hp_snmp_provisioning_driver.py
- etc/ml2_conf_hp.ini
Added the polling & snmp request  parameters in ml2_conf_hp.ini
> Added the configuration parameters for the BNP

- baremetal_network_provisioning/db/bm_nw_provision_db.py
- baremetal_network_provisioning/drivers/discovery_driver.py
- baremetal_network_provisioning/drivers/hp/hp_snmp_provisioning_driver.py
Initial code for snmp polling of port status.
> Initial code for snmp polling of port status.

- baremetal_network_provisioning/drivers/hp/hp_snmp_provisioning_driver.py
- etc/ml2_conf_hp.ini
Checking old and new values before updating port status.
Added log when port status is updated.
> Fix for CR ID 189969.

- baremetal_network_provisioning/drivers/hp/hp_snmp_provisioning_driver.py
- baremetal_network_provisioning/tests/unit/drivers/hp/test_hp_snmp_provisioning_driver.py
This includes the validation defect fixes and unit test cases .
> Mechanism Driver defect fixed and UT

- baremetal_network_provisioning/db/bm_nw_provision_db.py
This fix is for handling the exception for invalid port name
> DB helper for query physical port fixed

- baremetal_network_provisioning/tests/unit/drivers/test_snmp_driver.py
> VNETEE-500: Unit tests for SNMP driver

- devstack/README.rst
- devstack/plugin.sh
- devstack/settings
This change supports the enablement for bnp code in devstack
> Devstack support for baremetal network provisoning

- devstack/README.rst
More concrete steps added in README.rst
> README.rst file modified to add more steps

- baremetal_network_provisioning/common/validators.py
- baremetal_network_provisioning/ml2/extensions/bnp_switch.py
Checking for unrecognized attribute
> Fix for bug VNETEE - 570

- baremetal_network_provisioning/common/constants.py
- baremetal_network_provisioning/common/validators.py
- baremetal_network_provisioning/db/bm_nw_provision_db.py
- baremetal_network_provisioning/ml2/extensions/bnp_credential.py
- baremetal_network_provisioning/ml2/hpe_ironic_credential_ext_driver.py
- devstack/README.rst
- devstack/plugin.sh
- devstack/settings
- setup.cfg
> Credential Create REST API's

- baremetal_network_provisioning/common/constants.py
- baremetal_network_provisioning/db/bm_nw_provision_db.py
- baremetal_network_provisioning/db/bm_nw_provision_models.py
- baremetal_network_provisioning/drivers/discovery_driver_api.py
- baremetal_network_provisioning/drivers/snmp_discovery_driver.py
- baremetal_network_provisioning/managers.py
- baremetal_network_provisioning/ml2/extensions/bnp_switch.py
- devstack/plugin.sh
- devstack/settings
- setup.cfg
bnp switch create code changes in accordance to 
- new db schema
- new CLI/REST interface
> bnp switch create code changes

- baremetal_network_provisioning/ml2/extensions/bnp_switch.py
on switch delete checking port_prov status
> on switch delete checking port_prov status

- baremetal_network_provisioning/ml2/mechanism_hpe.py
Exception handled for invalid provisioning credentials in provisioning driver
> Exception handled for invalid prov credentials

- baremetal_network_provisioning/db/bm_nw_provision_db.py
- baremetal_network_provisioning/ml2/extensions/bnp_switch.py
1. Switch create validation for discovery protocol name and id
2. Switch delete support based on name
3. Switch delete validation handled for multiple same names
4. Implemented DB helper to support above fixes.
> Switch create validation handled

- baremetal_network_provisioning/common/validators.py
- baremetal_network_provisioning/db/bm_nw_provision_db.py
- baremetal_network_provisioning/drivers/port_provisioning_driver.py
- baremetal_network_provisioning/drivers/snmp_discovery_driver.py
- baremetal_network_provisioning/drivers/snmp_provisioning_driver.py
- baremetal_network_provisioning/managers.py
- baremetal_network_provisioning/ml2/extensions/bnp_switch.py
- baremetal_network_provisioning/ml2/mechanism_hpe.py
- baremetal_network_provisioning/tests/unit/db/test_bm_nw_provision_db.py
1. This change is to fix the existing issue in loading the family for discovery and provisioning
2 VNETEE-891 defect fixed where Incorrect HTTP responded when switch is created with non existing discovery creds
> Discovery & Provisioning Driver Family  support 

- baremetal_network_provisioning/db/bm_nw_provision_db.py
- baremetal_network_provisioning/drivers/snmp_provisioning_driver.py
- baremetal_network_provisioning/ml2/extensions/bnp_switch.py
> importing from neutron._i18n instead neutron.i18n
